version: '3.8'

services:

  # ===== Laravel =====
  laravel:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - fab_network
    depends_on:
      - mysql

  # ===== Nginx =====
  webserver:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fab_network
    depends_on:
      - laravel

  # ===== Express =====
  express:
    image: node:20
    container_name: express_app
    working_dir: /usr/src/app
    volumes:
      - ./express:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - fab_network

  # ===== MySQL =====
  mysql:
    image: mysql:8.0
    container_name: fab_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idmall
      MYSQL_USER: idmall_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fab_network

networks:
  fab_network:

volumes:
  db_data:
